i163 - Creating project container
Northeastern-Electric-Racing/PM-Dashboard-v2 pull request #191
Opened 2021-05-07 04:15 UTC by lpfahler16

Should be all set except for some testing trouble I am having. I return a loading p tag if the project is undefined. It seems that this happens very briefly before displaying the full project container. This is causing the tests to fail. Should this be something I worry about? I wasn't sure since we had discussed that the tests will likely change anyway. Thanks! Closes #163. Closes #130 
<img width="1440" alt="Screen Shot 2021-05-06 at 11 33 39 PM" src="https://user-images.githubusercontent.com/46872232/117397034-38d3db80-aec9-11eb-9238-37f4bc5257b5.png">

2021-05-07 05:25 UTC, jamescd18 requested changes
Added a couple review comments. Use `waitFor` to get those tests to pass. Otherwise it looks pretty great! Awesome job Logan!

2021-05-07 05:25 UTC, jamescd18 commented on src/components/project-details/project-details.module.css
> +}*/
Just go ahead and delete this instead of commenting it out.

2021-05-07 05:25 UTC, jamescd18 commented on src/containers/project-container/project-container.test.tsx
> +import { render, screen, waitFor } from '@testing-library/react';
use waitFor to delay execution of test assertions until certain stuff happens. Be sure to mark the test case method as async. `await waitFor(() => screen.getByText('1.1.0 - Impact Attenuator'))`

2021-05-07 05:25 UTC, jamescd18 commented on src/containers/project-container/project-container.tsx
> +import { WbsNumber } from 'utils/src';
items imported from the utils folder should always be imported via the utils package like so:
```suggestion
import { WbsNumber } from 'utils';
```
combine with line 9 too

2021-05-07 05:25 UTC, jamescd18 commented on src/containers/project-container/project-container.tsx
> +import { wbsPipe } from '../../shared/pipes';
I recommend putting this import line right after the other shared folder import, and place both of the shared folder imports after the utils package import.

2021-05-07 05:25 UTC, jamescd18 commented on src/containers/project-container/project-container.tsx
> +      console.log(response.data);
remove?

2021-05-07 05:25 UTC, jamescd18 commented on src/pages/wbs-details/wbs-details.tsx
> +      <p className={styles.describe}>{type}</p>
why place `{type}` within a <p> tag?

2021-05-27 02:59 UTC, lpfahler16 commented
I changed the container to use the services and it is working now. Here is an updated screenshot.
<img width="745" alt="Screen Shot 2021-05-26 at 10 58 25 PM" src="https://user-images.githubusercontent.com/46872232/119759231-e35e6f00-be75-11eb-9420-1103a9f1226c.png">

2021-05-27 04:42 UTC, jamescd18 approved these changes

2021-05-27 04:43 UTC, merged