making standard form field
Northeastern-Electric-Racing/PM-Dashboard-v2 pull request #313
Opened 2021-08-21 18:02 UTC by VerySeriousHireableAccount

closes #193 Standard Change Request Form Fields

2021-08-21 18:03 UTC, VerySeriousHireableAccount commented
![image](https://user-images.githubusercontent.com/41461150/130331067-cef18965-f5de-4318-874d-6bd6334af0cf.png)

2021-08-21 18:40 UTC, jamescd18 requested changes
This is amazing! Really well done! Just a few suggestions for customizing the IDs, adjusting the padding, and fixing some lint errors.

2021-08-21 18:40 UTC, jamescd18 commented on src/components/change-requests/new-change-request/new-change-request-page/standard-form-field/standard-form-field.tsx
> +        <Form.Group controlId="exampleForm.ControlTextarea1">
replace placeholder controlIds with meaningful ids for each form field. This one could probably be "newCR.what" and other fields would have "what" replaced with the field name

2021-08-21 18:40 UTC, jamescd18 commented on src/components/change-requests/new-change-request/new-change-request-page/standard-form-field/standard-form-field.tsx
> +      <Form className={'px-4'}>
form should be constructed higher up in the component tree

2021-08-21 18:40 UTC, jamescd18 commented on src/components/change-requests/new-change-request/new-change-request-page/standard-form-field/standard-form-field.tsx
> +    <div className={'row'}>
add some margin on the top and bottom

2021-08-21 18:40 UTC, jamescd18 commented on src/components/change-requests/new-change-request/new-change-request-page/standard-form-field/standard-form-field.tsx
> +                <Form.Control as="select" custom>
add unique Ids to each input box

2021-08-21 18:40 UTC, jamescd18 commented on src/components/change-requests/new-change-request/new-change-request-page/standard-form-field/standard-form-field.tsx
> +        <Form.Control type="text" />
add unique Id

2021-08-21 18:40 UTC, jamescd18 commented on src/components/change-requests/new-change-request/new-change-request-page/standard-form-field/standard-form-field.tsx
> +
remove extra line

2021-08-21 18:40 UTC, jamescd18 commented on src/components/change-requests/new-change-request/new-change-request-page/standard-form-field/standard-form-field.tsx
> +                  {exampleAllWorkPackages.map((p) => (
needs key field set

2021-08-28 18:29 UTC, jamescd18 commented on src/components/change-requests/new-change-request/new-change-request-page/standard-form-fields/standard-form-fields.test.tsx
> +});
```suggestion
});

```

2021-08-28 18:50 UTC, jamescd18 approved these changes

2021-08-28 18:50 UTC, merged