#310 home useful links
Northeastern-Electric-Racing/PM-Dashboard-v2 pull request #331
Opened 2021-09-10 22:21 UTC by lpfahler16

Here is a rough draft of issue 310. I'm hoping for guidance on additional styling (how it should look and where it should be). Thanks!

Closes #310
<img width="1440" alt="Screen Shot 2021-09-09 at 5 02 09 PM" src="https://user-images.githubusercontent.com/46872232/132923626-3db3cce8-7897-49ed-a943-7b64deb9e44d.png">

2021-09-10 23:19 UTC, jamescd18 requested changes
I love it! It's really great so far and will be super useful for everyone to have quick access to common items.

I included a bunch of suggestions in the code including a bit of styling with the page block component. I was thinking we might want to consider trying to make it two columns with responsive breakpoints so that it will go to 1 column when the screen is narrow

2021-09-10 23:19 UTC, jamescd18 commented on src/components/home/useful-links/useful-links.tsx
> +          <a className={styles.link} href="https://twitter.com/" target="_blank" rel="noreferrer">
I believe we have a link pipe that can be used to abstract the creation of an anchor tag

2021-09-10 23:19 UTC, jamescd18 commented on src/components/home/useful-links/useful-links.tsx
> +    <div>
Let's use a page block component to nicely style this section on the home page

2021-09-10 23:19 UTC, jamescd18 commented on src/components/home/useful-links/useful-links.tsx
> +          <a className={styles.link} href="https://twitter.com/" target="_blank" rel="noreferrer">
Actual link: https://forms.gle/6ztRoa1iL7p1KHwP6

2021-09-10 23:19 UTC, jamescd18 commented on src/components/home/useful-links/useful-links.tsx
> +          <a className={styles.link} href="https://twitter.com/" target="_blank" rel="noreferrer">
Actual link: https://docs.google.com/document/d/1M5Ldy9L1BifBo18tdKpv3CH-frRneyEK26hUXbtMg7Q/edit

2021-09-10 23:19 UTC, jamescd18 commented on src/components/home/useful-links/useful-links.tsx
> +      </ul>
Let's add the following links:
- Reimbursement guidelines: https://docs.google.com/document/d/1HvLnVNzZTftgoAXppIEp-gTmUBQGt-V6n97prziWWrs/edit
- McMaster order sheet: https://docs.google.com/spreadsheets/d/1kqpnw8jZDx2GO5NFUtqefRXqT1XX46iMx5ZI4euPJgY/edit

2021-09-10 23:19 UTC, jamescd18 commented on src/components/home/useful-links/useful-links.tsx
> +          <a className={styles.link} href="https://twitter.com/" target="_blank" rel="noreferrer">
Actual link: https://docs.google.com/spreadsheets/d/1av0ReONZF3r82kCvkUEGl3uue4jfQgbw-KQDZnsejPQ/edit

2021-09-10 23:19 UTC, jamescd18 commented on src/components/home/useful-links/useful-links.test.tsx
> +    <RouterWrapper>
Is router wrapper necessary?

2021-09-16 07:22 UTC, jamescd18 requested changes
It's looking a lot better! I love the usage of arrays for additional flexibility. A few more minor changes would be good, along with the side-by-side display I know you're looking in to.

One note (I mentioned this at the first Saturday learning session), you generally never want to commit changes to a package-lock.JSON file unless you are also explicitly making changes to the associated package.JSON file. In this case, it is probably not worth trying to fix it, just keep it in mind for the future.

Lastly, I would love it if you could add the following links to the "Other" section:
- Individual Member Goals Form - https://forms.gle/MAZJSFcMBjn44p3F6
- Manufacturing Request Form - https://forms.gle/vJmTRt2xnzGa7akb8

2021-09-16 07:22 UTC, jamescd18 commented on src/components/home/home.tsx
> +      <UsefulLinks></UsefulLinks>
When you have no child components, utilize the single tag syntax rather than the double (opening and closing) tag syntax.

2021-09-16 07:22 UTC, jamescd18 commented on src/components/home/useful-links/useful-links.tsx
> +import styles from './useful-links.module.css';
My personal preference is to always have the style import be the very last import statement.

2021-09-16 07:22 UTC, jamescd18 commented on src/components/home/useful-links/useful-links.tsx
> +    linkPipe(
Reimbursement guidelines should go under finance links

2021-09-16 07:22 UTC, jamescd18 commented on src/components/home/useful-links/useful-links.tsx
> +    <PageBlock
You should be able to use the single tag syntax here too.

2021-09-21 01:44 UTC, jamescd18 requested changes
Looking better! I recommend only resolving a review comment after making a commit to fix the issue. Also, in the future try not to commit the package-lock.json file unless you're explicitly making changes to the package.json, but we can leave it for this PR.

2021-09-21 14:09 UTC, lpfahler16 commented
It should be all set! Here is a screenshot of the completed component. A third or fourth category of links should be able to be easily added as well.
<img width="1440" alt="Screen Shot 2021-09-21 at 10 08 31 AM" src="https://user-images.githubusercontent.com/46872232/134186204-a086fd4b-d371-4966-a4c7-6a7e1e89c295.png">

2021-09-21 14:59 UTC, jamescd18 commented on src/components/home/home.tsx
> +      <UsefulLinks></UsefulLinks>
This one?

2021-09-21 15:00 UTC, jamescd18 requested changes
Almost there. One item unresolved.

2021-09-21 23:52 UTC, jamescd18 approved these changes
Awesome! This is going to be amazingly useful!

2021-09-21 23:52 UTC, merged