#320 - Add Summary to Project type & page
Northeastern-Electric-Racing/PM-Dashboard-v2 pull request #336
Opened 2021-09-20 20:59 UTC by RChandler234

We added summary to the Project page below the project details as a PageBlock and changed the Project type to include the summary. We also updated the dummy data to include dummy summary data.

2021-09-20 22:55 UTC, acd124 commented
The p tag could probably be changed to an empty element, whether this is done or not is up to whether the format of the p tag is wanted or not and the preference for style.

2021-09-21 06:16 UTC, jamescd18 requested changes
This looks great! One small edit and it should be ready to go!

Few notes:
- be sure to attach a screenshot of the updated UI since your ticket required changing the UI
- be sure to add me/kincent to the PR for review in addition to ping'ing on slack

2021-09-21 06:16 UTC, jamescd18 commented on src/components/projects/wbs-details/project-container/project-container.tsx
> +  console.log(data!.summary);
Be sure to not leave extraneous `console.log` statements in the code.

2021-09-21 06:20 UTC, jamescd18 commented
Also be sure to link the associated issue on the right!

2021-09-21 07:36 UTC, jpwaves commented
> Also be sure to link the associated issue on the right!

Just added issue #320 to "Linked Issues" category on the right side-bar.

2021-09-21 16:27 UTC, acd124 commented
With p tag 
<img width="691" alt="Screen Shot 2021-09-21 at 12 25 33 PM" src="https://user-images.githubusercontent.com/51572473/134209639-ae8c3755-0380-400f-b17b-242c47f35da9.png">
Without p tag 
<img width="679" alt="Screen Shot 2021-09-21 at 12 25 49 PM" src="https://user-images.githubusercontent.com/51572473/134209718-6c106f91-4b68-4985-bba7-1680ae93e4a4.png">

2021-09-22 01:39 UTC, jamescd18 approved these changes
Ah yes, without the p tag is much better since it eliminates the unnecessary padding on the bottom and the text looks no different. Nice job guys!

2021-09-22 01:39 UTC, merged