#357 Project Shared Tools
Northeastern-Electric-Racing/PM-Dashboard-v2 pull request #378
Opened 2021-10-30 22:50 UTC by acd124

Closes #357

We have added the projects transformer and updated the types to align the database and interfaces a bit more. We added a workPackageSummary type to replace the workPackage type on Projects, so projects is not transforming work packages and everything in them as well.

2021-11-01 23:27 UTC, acd124 commented
We updated front end type changes and added a front end workPackageSummary transformer to line up with the backend changes. There are still 2 places where the changes making properties optional cause errors in the front end which we were not sure how we might fix, so we left them alone for now.
`src/components/projects/wbs-details/project-container/project-details/project-details.tsx`
`src/components/projects/projects-table/projects-table/projects-table.test.tsx`

2021-11-02 02:20 UTC, jamescd18 requested changes
Looks pretty good so far. One naming suggestion, and it'd be great to get those errors you mentioned resolved.

2021-11-02 02:20 UTC, jamescd18 commented on src/components/projects/wbs-details/project-container/project-container.tsx
> +            {data!.workPackages.map((ele: WorkPackageSum) => (
Personally, I'd go with `WPSummary` instead, because `WP` is a common abbreviation for Work Package the application.

2021-11-02 02:20 UTC, jamescd18 commented on src/components/projects/wbs-details/project-container/work-package-summary/work-package-summary.tsx
> +import { WorkPackageSummary as WorkPackageSum } from 'utils';
Same as before

2021-11-06 19:47 UTC, jamescd18 approved these changes
Looks great! Nothing stands out to me, so if it's all ready, feel free to merge

2021-11-06 23:11 UTC, merged