#364 - started implementation
Northeastern-Electric-Racing/PM-Dashboard-v2 pull request #427
Opened 2022-01-11 03:54 UTC by anthonybernardi

initial implementation, not totally done yet but want some feedback on what I have so far

2022-01-13 20:55 UTC, jamescd18 requested changes
Great start! Let me know if any of the review notes are confusing. Mainly it's minor TypeScript syntax cleanup and minor changes.

2022-01-13 20:55 UTC, jamescd18 commented on src/backend/functions/work-packages-create.ts
> +    // get the corresponding project so we can find the next wbs number
```suggestion
const createWorkPackage: Handler = async ({ body }, _context) => {
    // get the corresponding project so we can find the next wbs number
```

2022-01-13 20:55 UTC, jamescd18 commented on src/backend/functions/work-packages-create.ts
> +          status: WBS_Element_Status.ACTIVE
this shouldn't be needed after we have #426

2022-01-13 20:55 UTC, jamescd18 commented on src/backend/functions/work-packages-create.ts
> +    const { wbsElement } = last;
can we inline these? place them where they get used instead of having separate variables?

2022-01-13 20:55 UTC, jamescd18 commented on src/backend/functions/work-packages-create.ts
> +
```suggestion
```

2022-01-13 22:47 UTC, jpwaves commented on src/backend/functions/work-packages-create.ts
> +
Isn't there a connect on line 66 to project? So, you don't need to connect the project again.

2022-01-16 02:58 UTC, jamescd18 requested changes
some lint errors, a new location for input schemas, and a minor fix to the api url string, but I understand it's a work-in-progress

2022-01-16 02:58 UTC, jamescd18 commented on src/utils/src/api-routes.ts
> +const WORK_PACKAGES_CREATE: string = `${WORK_PACKAGES}/create`;
```suggestion
const WORK_PACKAGES_CREATE: string = `${WORK_PACKAGES}-create`;
```

2022-01-16 02:58 UTC, jamescd18 commented on src/backend/functions/work-packages-create.ts
> +const inputSchema = {
check out this new way where we're putting it in the `utils` package

https://github.com/Northeastern-Electric-Racing/PM-Dashboard-v2/blob/dca5d7b78d63c608c9cac301fdd9b27361f35cd4/src/backend/functions/change-requests-review.ts#L43

2022-01-16 02:58 UTC, jamescd18 commented on src/backend/functions/work-packages-create.ts
> +        connect: body.wbsElementIds.map((ele: any) => {
watch out for lint errors

2022-01-20 17:59 UTC, jamescd18 requested changes
making great progress here! I think it's nearing ready, just a couple minor things. Also, if you could test it and send screenshots of that, that would be great. screenshots of a good payload you sent and then screenshot of the response, maybe also screenshot of the new item in the database table too

2022-01-20 17:59 UTC, jamescd18 commented on src/backend/functions/work-packages-create.ts
> +import { PrismaClient, WBS_Element_Status } from '@prisma/client';
unused import

2022-01-20 17:59 UTC, jamescd18 commented on src/backend/functions/work-packages-create.ts
> +import { workPackageInputSchemaBody } from 'utils/src/types/work-package-types';
if importing from `utils`, it should always be `from 'utils';`

2022-01-20 17:59 UTC, jamescd18 commented on src/backend/functions/work-packages-create.ts
> +  ].wbsElement;
the highest `workPackageNumber` is not guaranteed to be the last element in the array of work packages.

2022-01-21 00:06 UTC, anthonybernardi commented
Here are the requested images:

This image shows the request url, body, and then the response using postman
<img width="1085" alt="create work package" src="https://user-images.githubusercontent.com/63663597/150441711-56db98e9-fbf2-46c6-b86a-75021f25e1df.png">

This image shows the new entry added in the Work_Packages table
<img width="928" alt="work package table" src="https://user-images.githubusercontent.com/63663597/150441705-0b5828f2-bd18-418f-943c-3362ef25d1dd.png">

2022-01-21 07:29 UTC, jamescd18 requested changes
A couple more items. Mainly hopefully fixing package.json

2022-01-21 07:29 UTC, jamescd18 commented on package.json
> +    "build": "npm ci && run-p build:**",
You might try replacing your package.json with the one from main because you ideally shouldn't have any changes

2022-01-21 07:29 UTC, jamescd18 commented on src/backend/functions/work-packages-create.ts
> +    ...project.workPackages.map((x) => {
I typically suggest more human-readable temp variables like pkg or ele

2022-01-21 07:29 UTC, jamescd18 commented on src/backend/functions/work-packages-create.ts
> +        connect: body.wbsElementIds.map((x: any) => {
Same on variable naming.

2022-01-21 19:23 UTC, jamescd18 approved these changes
LGTM!

2022-01-21 19:23 UTC, merged