#435-updated-scope-change-request-and-added-design-item
Northeastern-Electric-Racing/PM-Dashboard-v2 pull request #493
Opened 2022-01-27 16:51 UTC by rishavsarma5

Here are screenshots of the changes implemented.
![change1](https://user-images.githubusercontent.com/76542282/151405016-f64881c9-f1df-4ba7-8922-bae0621f3762.png)

![image](https://user-images.githubusercontent.com/76542282/151405207-75042a9f-b9f0-498d-b3f5-10ae7991dce8.png)

Is there any more that I need to have do?

2022-01-27 19:14 UTC, jamescd18 requested changes
Adding design is not so simple. there's enums and prisma schema that need to be updated to fully propagate this across the whole application

2022-01-27 19:14 UTC, jamescd18 commented on src/components/change-requests/new-change-request/new-change-request-page/standard-form-fields/standard-form-fields.tsx
> +            ].map((type) => (
this should be driven off of the underlying enum using `Object.values()`

2022-01-28 00:32 UTC, jamescd18 requested changes
There's more than needs to be changed because this one single form checkbox on the front-end impacts everything through the entire stack to the database:

- [ ] [the enum in utils](https://github.com/Northeastern-Electric-Racing/PM-Dashboard-v2/blob/aeb832841b5e1035d88de459bda5eeb804226b09/src/utils/src/types/change-request-types.ts#L57)
- [ ] [the enum in prisma schema](https://github.com/Northeastern-Electric-Racing/PM-Dashboard-v2/blob/aeb832841b5e1035d88de459bda5eeb804226b09/src/backend/prisma/schema.prisma#L35)
- [ ] maybe more I'm forgetting

2022-01-28 00:32 UTC, jamescd18 commented on src/components/change-requests/new-change-request/new-change-request-page/standard-form-fields/standard-form-fields.tsx
> +import { ChangeRequestReason } from 'utils/lib/types/change-request-types';
```suggestion
import { ChangeRequestReason } from 'utils';
```

things from utils should only ever be imported with `'utils'`

2022-01-28 05:16 UTC, rishavsarma5 commented
Im not completely sure what happened with the second commit

2022-01-29 08:52 UTC, jamescd18 approved these changes
LGTM

2022-01-29 08:52 UTC, merged