#340-changed-vs-code-string-in-onboarding
Northeastern-Electric-Racing/PM-Dashboard-v2 pull request #524
Opened 2022-02-12 18:33 UTC by rishavsarma5

I updated the onboarding doc to make the json-string a bit better formatted.

2022-02-12 18:35 UTC, acd124 requested changes
Cool stuff

2022-02-12 18:35 UTC, acd124 commented on docs/Onboarding.md
>  },
Remove the comma, since json doesn't allow trailing commas

2022-02-12 18:35 UTC, acd124 commented on docs/Onboarding.md
> +"[typescriptreact][typescript]": {
Requires testing to see if this works for some older vscode versions

2022-02-14 02:34 UTC, jamescd18 reviewed
Is this just to make it look better? Honestly doesn't seem worth the effort if there's any real worry that it might not be compatible

2022-02-14 05:56 UTC, rishavsarma5 commented
This was just the demo ticket and PR I did for my presentation on Saturday. Alexander thought it would be a good change to do. You can just delete the PR.

2022-02-14 07:04 UTC, jamescd18 commented
Oh lol. This is perfect for that! Just drop that in the PR description. Here's what it looks like to close an example PR

2022-02-14 07:04 UTC, closed without merging