#485 update new cr fields
Northeastern-Electric-Racing/PM-Dashboard-v2 pull request #534
Opened 2022-02-19 20:39 UTC by syedDS

new C_R update from initiation to activation on type

2022-02-21 00:04 UTC, syedDS commented
The code tested on the local repo didnt gave any error but is giving after PR , can someone review it

2022-02-21 07:24 UTC, jamescd18 commented
It looks like you changed the `package.json` and `package-lock.json` files, both of which you do not want to be changing. This potentially is part of why it broke.

2022-03-01 23:27 UTC, jamescd18 requested changes
Awesome! Just one small change for this code. The bigger thing is that this PR has a very messy commit history and I don't see any of the commits being tagged with the ticket number. Given how small the code change is, I would love for you to create a fresh new branch, make just 1 commit that has the ticket number as described in the contributor guide, and open a new PR. I think this is a really good learning experience because this PR here allowed you to figure out how things work and get feedback, and then the fresh new PR will be the one that we actually approve and merge into main. If you have any questions or if anything is confusing, reach out to your tech lead on Slack. Thank you!

2022-03-01 23:27 UTC, jamescd18 commented on src/components/change-requests/new-change-request/new-change-request-page/common-form-fields/common-form-fields.tsx
> +            t // change from intiation -> Activation
This comment looks like it's specific to this pull request so you'll want to remove it

2022-03-08 23:51 UTC, closed without merging