#370 Project Edit Form Validation
Northeastern-Electric-Racing/PM-Dashboard-v2 pull request #590
Opened 2022-03-26 16:56 UTC by VatsalMehta27

## Changes

Added validation to fields in the project edit form, by adding a validation function that checks the required fields when the form is submitted (on clicking the save button). 
Used try/catch when creating a new URL object for link validation.
Added "required" to the form component to ensure that fields aren't left empty.

## Notes

N/A

## Test Cases

N/A

## Screenshots (if applicable)

**Budget Validation:**
<img width="1280" alt="Budget can't be negative" src="https://user-images.githubusercontent.com/66726182/160249181-8ad4b99a-a867-4e70-b962-28e09cdf73a6.png">

<img width="613" alt="Budget is required" src="https://user-images.githubusercontent.com/66726182/160249192-85bbea4a-4d8b-4970-9b8e-6c5684e33d88.png">

**URL Validation:**
<img width="1280" alt="URL validation" src="https://user-images.githubusercontent.com/66726182/160249198-9c92e5ac-3c28-45b9-9da8-31805f86557c.png">

<img width="1210" alt="URL is required" src="https://user-images.githubusercontent.com/66726182/160249220-22af3f84-8098-4a06-80d7-a7ca082f7a26.png">

**Project Summary Validation:**
<img width="1230" alt="Project summary is required" src="https://user-images.githubusercontent.com/66726182/160249234-bc8346f7-19bf-4f4e-abb7-d7e9fb4e7bbc.png">

**Bullet Validation:**
<img width="1240" alt="Bullets can't be empty strings" src="https://user-images.githubusercontent.com/66726182/160249240-f3dd9431-0c17-4f6e-95ce-1a29a3f3190d.png">

## To Do

N/A

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://github.com/Northeastern-Electric-Racing/PM-Dashboard-v2/blob/main/docs/ContributorGuide.md) and reach out to your squad if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors
- [ ] No newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (if applicable)
- [ ] Remove any not-applicable sections
- [ ] Assign the PR to yourself
- [ ] PR is linked to the ticket
- [ ] No `package-lock.json` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack

Closes #370

2022-03-27 17:20 UTC, anthonybernardi reviewed
Looks good to me, checked it on my computer and it seems to work too (except for the url thing I mentioned but idk if we care enough to fix that).

The main problem is commit formatting! They need to be in the format "#370 - dlskjflkds"!

2022-03-28 03:25 UTC, jamescd18 commented on src/components/projects/project-edit-form/project-edit-container/project-edit-details/project-edit-details.tsx
> +// import { useState } from 'react';
yep

2022-03-28 03:28 UTC, jamescd18 commented on src/components/projects/project-edit-form/project-edit-container/project-edit-container.tsx
> +      try {
We only want to allow `YouTube.com` if that works properly on the project page displaying links. If it doesn't work, then just don't allow links without the prefix. It's a tiny UX difference so I don't particularly care. We can push users to always include the prefix if needed.

2022-03-28 03:36 UTC, jamescd18 requested changes
I like this! Really great start! There's a few different changes I've left in review comments.

2022-03-28 03:36 UTC, jamescd18 commented on src/components/projects/project-edit-form/project-edit-container/project-edit-container.tsx
> +  // const [validated, setValidated] = useState(false);
if not used, remove

2022-03-28 03:36 UTC, jamescd18 commented on src/components/projects/project-edit-form/project-edit-container/project-edit-container.tsx
> +
let's remove the empty lines between all these state updating functions

2022-03-28 03:36 UTC, jamescd18 commented on src/components/projects/project-edit-form/project-edit-container/project-edit-container.tsx
> +  const notEmptyString = (val: string) => val !== "";
with type inference, you might be able to drop the type annotation but not sure, just wondering
```suggestion
  const notEmptyString = s => s !== '';
```

2022-03-28 03:36 UTC, jamescd18 commented on src/components/projects/project-edit-form/project-edit-container/project-edit-container.tsx
> +  const notEmptyString = (val: string) => val !== "";
also do you have prettier styling applied?

2022-03-28 03:36 UTC, jamescd18 commented on src/components/projects/project-edit-form/project-edit-container/project-edit-container.tsx
> +    }
this can be done a different and better way by adding a `min={0}` prop to the react bootstrap form control.

2022-03-28 03:37 UTC, jamescd18 commented
> - [x] All commits are tagged with the ticket number

This is incorrect. I don't see any of your commits being tagged with ticket number.

2022-03-30 16:10 UTC, closed without merging