#698 - edit schema
Northeastern-Electric-Racing/PM-Dashboard-v2 pull request #721
Opened 2022-06-15 23:35 UTC by RChandler234

## Changes

Edited the prisma schema to incorporate the risk log

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://github.com/Northeastern-Electric-Racing/PM-Dashboard-v2/blob/main/docs/ContributorGuide.md) and reach out to your squad if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors
- [ ] No newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (if applicable)
- [ ] Remove any not-applicable sections
- [ ] Assign the PR to yourself
- [ ] PR is linked to the ticket
- [ ] No `package-lock.json` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack

Closes # (issue #)

2022-06-16 16:46 UTC, jamescd18 commented
This looks good to me!

2022-06-16 16:46 UTC, jamescd18 approved these changes

2022-06-16 20:09 UTC, jamescd18 requested changes
just realized there’s like 4 things missing. I realized that because Risks aren’t gonna be facilitated through the change log, we wanna record more info:

- who created the risk
- who resolved the risk
- when the risk was resolved
- who deleted the risk

2022-06-27 04:22 UTC, RChandler234 commented
Ended up scrapping the uuid investigation in this PR, because I couldn't get the uuid's to auto-generate locally, and I wanna get this ticket done to unblock others; I'll open another ticket under this epic to look into the change before we deploy the feature and start getting risk data (probably wanna talk to @jamescd18 when we both have time because not sure how best to test that this works as we expect)

2022-06-27 04:32 UTC, jamescd18 approved these changes

2022-06-27 16:26 UTC, anthonybernardi submitted a review, later dismissed
nice

2022-06-27 17:30 UTC, jamescd18 requested changes

2022-06-27 17:30 UTC, jamescd18 commented on src/backend/prisma/seed.ts
> +    await prisma.risk.create({ data: { ...seedRisk } });
Pretty sure you're gonna need to do a connect to link it up with the user creating it. See change requests for an example probably

2022-06-27 17:30 UTC, jamescd18 commented on src/backend/prisma/seed.ts
> +    await prisma.risk.create({ data: { ...seedRisk } });
Also might make more sense to have this come after projects

2022-06-27 17:30 UTC, jamescd18 commented on src/backend/prisma/seed.ts
> +    await prisma.risk.create({ data: { ...seedRisk } });
And probably connect to the project

2022-06-29 08:45 UTC, jamescd18 approved these changes

2022-06-29 08:45 UTC, merged