#666 - Removed the spread operator wherever it appeared in the code
Northeastern-Electric-Racing/PM-Dashboard-v2 pull request #747
Opened 2022-06-23 00:50 UTC by tigerhippo

## Changes

I removed the spread operator wherever it appeared in the code. 

## Notes

I am not sure what to input for the fields projectLead and projectManager on lines 155 and 156 respectively. I did workPackage.wbsElement.projectLead and workPackage.wbsElement.projectManager (which should work because the WbsElement interface had all of these fields). However, the error message stated that the wbsElement did not have any of these fields.

I still need to test my code, but it would be great if someone could take a look at all the places where I removed the spread operator to see if I did it correctly!

2022-06-23 06:17 UTC, jamescd18 requested changes
Looking good! Give those a try and attach screenshots of errors if you run into any. You can also still commit + push your code and see if the automated test runner will fail or not. If it doesn't, it's probably still good code.

2022-06-23 06:17 UTC, jamescd18 commented on src/backend/functions/projects.ts
> +        projectManager: null,
```suggestion
        projectManager: workPackage.wbsElement.projectManager,
```

2022-06-23 06:17 UTC, jamescd18 commented on src/backend/functions/projects.ts
> +        //...workPackage.wbsElement,
```suggestion
```

2022-06-25 14:48 UTC, anthonybernardi requested changes
great work! the only thing I want to add from James' review is that you committed the package-lock.json file which should not be committed except in very specific circumstances.

To uncommit this, you can essentially commit the current "main" version of the package-lock to your branch. This way, the package-lock will be the same as the one on main and then it wont be a change if that makes sense

2022-07-16 18:30 UTC, anthonybernardi commented
i swear the package-lock is the exact same as the one on main. Go check line ~1496 for proof that the diff is wrong

2022-07-23 18:51 UTC, anthonybernardi commented
![image](https://user-images.githubusercontent.com/63663597/180618997-e11cee42-85da-4937-8762-9bba96da9276.png)

this makes no sense and it's the same as on main so im merging this

2022-07-23 18:51 UTC, anthonybernardi approved these changes

2022-07-23 18:52 UTC, merged