#765 remove empty css files
Northeastern-Electric-Racing/PM-Dashboard-v2 pull request #766
Opened 2022-07-18 05:14 UTC by RChandler234

## Changes

Removed Empty CSS files

## Test Cases

Smoke test to make sure that nothing in the application is broken/ looks weird

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://github.com/Northeastern-Electric-Racing/PM-Dashboard-v2/blob/main/docs/ContributorGuide.md) and reach out to your squad if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors
- [ ] No newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (if applicable)
- [ ] Remove any not-applicable sections
- [ ] Assign the PR to yourself
- [ ] PR is linked to the ticket
- [ ] No `package-lock.json` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack

Closes # (issue #)

2022-07-18 06:30 UTC, jamescd18 requested changes
Is this everything? Just one file that looks like it should have been deleted but was just edited?

2022-07-18 06:30 UTC, jamescd18 commented on src/frontend/pages/ProjectsPage/projects-table/projects-table.module.css
> + */
Delete this file too?

2022-07-19 01:39 UTC, anthonybernardi commented on src/frontend/pages/ProjectsPage/projects-table/projects-table.module.css
> + */
100% go for it

2022-07-19 01:40 UTC, anthonybernardi commented
Nothing better than a PR that looks like this: 

<img width="173" alt="Screen Shot 2022-07-18 at 9 39 57 PM" src="https://user-images.githubusercontent.com/63663597/179645586-0d6654ad-ae20-46d3-9ed0-1b85a4275a7b.png">

2022-07-20 00:30 UTC, jamescd18 approved these changes
LGTM!

2022-07-20 17:23 UTC, RChandler234 commented
I couldn't move all the css over, some was too complex to put into a jsx object; I suggest we make a stylesheets folder for the frontend and move the remaining ones there for now and try to find a more consistent way to handle having css in a tsx file (there are ways, but it'd involved adding more packages/ bigger changes, so I don't wanna do it rn); that or if this way looks too inconsistent lmk, and we can just do removing the unused stylesheets for this MR and handle moving the CSS in another one. @jamescd18 @anthonybernardi

2022-07-20 21:43 UTC, jamescd18 commented
I see nothing wrong with only have a few components have CSS files, I don't think there's any need to make them be in a separate folder.

2022-07-23 19:01 UTC, anthonybernardi approved these changes
i'm good with this. we can deal with the last few files in a separate ticket. I wouldn't mind a stylesheets folder actually since my plan is to move all the tests out too

2022-07-23 19:03 UTC, merged